config/routes.rb
Rails.application.routes.draw do
  resources :order_lines
  resources :orders
  resources :products
  get 'catalogs/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
    
end

class Order < ActiveRecord::Base
    has_many :order_line, dependent: :destroy
end

app/models/order_line.rb
class OrderLine < ApplicationRecord
  belongs_to :Product
  belongs_to :Order
end

app/models/product.rb
class Product < ApplicationRecord
    
end

class Product < ActiveRecord
    has_many :order_line

    before_destroy :ensure_not_referenced_by_any_order_line

    private

        def ensure_not_referenced_by_any_order_line
            if order_line.empty?
                return true
            else
                errors.add( :base, 'Line Item present')
                return false
            end
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/current_order.rb
module CurrentOrder
    extended ActiveSupport::concern

    private

    def set_order
        @order = Order.find(session[:order_id])
    rescue ActiveRecord::RecordNotFound
        @order = Order.creat
        session [:order_id] = @order.id
    end


end

app/controllers/order_lines_controller.rb
class OrderLinesController < ApplicationController
  before_action :set_order_line, only: %i[ show edit update destroy ]

  # GET /order_lines or /order_lines.json
  def index
    @order_lines = OrderLine.all
  end

  # GET /order_lines/1 or /order_lines/1.json
  def show
  end

  # GET /order_lines/new
  def new
    @order_line = OrderLine.new
  end

  # GET /order_lines/1/edit
  def edit
  end

  # POST /order_lines or /order_lines.json
  def create
    @order_line = OrderLine.new(order_line_params)

    respond_to do |format|
      if @order_line.save
        format.html { redirect_to @order_line, notice: "Order line was successfully created." }
        format.json { render :show, status: :created, location: @order_line }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_lines/1 or /order_lines/1.json
  def update
    respond_to do |format|
      if @order_line.update(order_line_params)
        format.html { redirect_to @order_line, notice: "Order line was successfully updated." }
        format.json { render :show, status: :ok, location: @order_line }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_lines/1 or /order_lines/1.json
  def destroy
    @order_line.destroy
    respond_to do |format|
      format.html { redirect_to order_lines_url, notice: "Order line was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_line
      @order_line = OrderLine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_line_params
      params.require(:order_line).permit(:Product_id, :Order_id)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]

  # GET /orders or /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1 or /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:price, :delivery_tax)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Produto Salvo com sucesso." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Produto atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Produto deletado com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:description, :order_number, :price, :stock, :take, :pay)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/order_lines_helper.rb
module OrderLinesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/catalog/index.html.erb
<p id="notice"><%= notice %></p>

<h1> Seu catálogo </h1>

<% cache ['Catalog', Product.lastest] do %>
    <% @products.each do |product| %>
        <% if product.stock != 0 %> 
            <tr>
                <td><%= product.description %></td>
                <td><%= product.order_number %></td>
                <td><%= product.price %></td>
                <td><%= product.stock %></td>
                <td><%= product.take %></td>
                <td><%= product.pay %></td>
                <td><%= form.label "quantidade:" %>
                <td><%= form.number_field @order_lines:amount %>
                <td><%= button_to 'adicionar produto', order_lines_path(product.id: product)%></td>
            </tr>
        <% end %>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MercadappChallenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/order_lines/_form.html.erb
<%= form_with(model: order_line) do |form| %>
  <% if order_line.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order_line.errors.count, "error") %> prohibited this order_line from being saved:</h2>

      <ul>
        <% order_line.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Product_id %>
    <%= form.text_field :Product_id %>
  </div>

  <div class="field">
    <%= form.label :Order_id %>
    <%= form.text_field :Order_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/order_lines/edit.html.erb
<h1>Editing Order Line</h1>

<%= render 'form', order_line: @order_line %>

<%= link_to 'Show', @order_line %> |
<%= link_to 'Back', order_lines_path %>

app/views/order_lines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Order Lines</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order_lines.each do |order_line| %>
      <tr>
        <td><%= order_line.Product_id %></td>
        <td><%= order_line.Order_id %></td>
        <td><%= link_to 'Show', order_line %></td>
        <td><%= link_to 'Edit', edit_order_line_path(order_line) %></td>
        <td><%= link_to 'Destroy', order_line, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order Line', new_order_line_path %>

app/views/order_lines/new.html.erb
<h1>New Order Line</h1>

<%= render 'form', order_line: @order_line %>

<%= link_to 'Back', order_lines_path %>

app/views/order_lines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @order_line.Product_id %>
</p>

<p>
  <strong>Order:</strong>
  <%= @order_line.Order_id %>
</p>

<%= link_to 'Edit', edit_order_line_path(@order_line) %> |
<%= link_to 'Back', order_lines_path %>

app/views/orders/_form.html.erb
<%= form_with(model: order) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :delivery_tax %>
    <%= form.text_field :delivery_tax %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Price</th>
      <th>Delivery tax</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.price %></td>
        <td><%= order.delivery_tax %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Price:</strong>
  <%= @order.price %>
</p>

<p>
  <strong>Delivery tax:</strong>
  <%= @order.delivery_tax %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> Produto não pode ser salvo:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "Descrição:"%>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label "Código de barras:" %>
    <%= form.number_field :order_number %>
  </div>

  <div class="field">
    <%= form.label "preço:" %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label "Estoque" %>
    <%= form.number_field :stock %>
  </div>

  <div>
    <strong>
      <%= "Caso não tenha promoção digite 1 em Leve e 1 em Pague" %>
    </strong>
  </div>

  <div class="field">
    <%= form.label "Leve" %>
    <%= form.number_field :take %>
  </div>

  <div class="field">
    <%= form.label "Pague:" %>
    <%= form.number_field :pay %>
  </div>

  <div class="actions">
    <%= form.submit "Criar produto" %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editando produto</h1>

<%= render 'form', product: @product %>

<%= link_to 'Mostrar', @product %> |
<%= link_to 'Voltar', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Produtos</h1>

<table>
  <thead>
    <tr>
      <th>Descrição</th>
      <th>Código de barras</th>
      <th>Preço</th>
      <th>Estoque</th>
      <th>Leve</th>
      <th>Pague</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.description %></td>
        <td><%= product.order_number %></td>
        <td><%= product.price %></td>
        <td><%= product.stock %></td>
        <td><%= product.take %></td>
        <td><%= product.pay %></td>
        <td><%= link_to 'Mostrar', product %></td>
        <td><%= link_to 'Editar', edit_product_path(product) %></td>
        <td><%= link_to 'Deletar', product, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo produto', new_product_path %>

app/views/products/new.html.erb
<h1>Novo produto</h1>

<%= render 'form', product: @product %>

<%= link_to 'Voltar', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descrição:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Código de barras:</strong>
  <%= @product.order_number %>
</p>

<p>
  <strong>Preço:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Estoque:</strong>
  <%= @product.stock %>
</p>

<p>
  <strong>Leve:</strong>
  <%= @product.take %>
</p>

<p>
  <strong>Pague:</strong>
  <%= @product.pay %>
</p>

<%= link_to 'Editar', edit_product_path(@product) %> |
<%= link_to 'Voltar', products_path %>